# Generated by Django 5.1.4 on 2025-02-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Укажите вашу страну', max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
