# Generated by Django 5.1.4 on 2024-12-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите название', max_length=150, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Введите описание', max_length=250, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=150, verbose_name='наименование')),
                ('description', models.TextField(help_text='Введите описание', max_length=250, verbose_name='описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, help_text='Введите цену', max_length=150, null=True, verbose_name='Цена')),
                ('created_at', models.DateField(blank=True, help_text='Введите дату создания', null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
