# Generated by Django 5.1.4 on 2025-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена'),
        ),
    ]
