# Generated by Django 4.2.2 on 2025-02-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
