# Generated by Django 4.2.2 on 2025-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_publication',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
    ]
